version: "3"

services:
  redis:
    container_name: logging_redis
    image: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --port 6379
    ports:
      - "6379:6379"
